version: "3.7"
services:
  postgresql:
    image: postgres:14
    environment:
      - "POSTGRES_USER=mars"
      - "POSTGRES_PASSWORD=mars"
    ports:
      - "5432:5432"
  redis:
    image: redis:6
    ports: 
        - "6379:6379"
  influxdb:
    image: influxdb:2.0
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=vertigo
      - DOCKER_INFLUXDB_INIT_PASSWORD=vertigo-password
      - DOCKER_INFLUXDB_INIT_ORG=vertigo
      - DOCKER_INFLUXDB_INIT_BUCKET=myApp
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=is4DQpHF8XkvNJRm5KNJOtjlKIpfVc2G
    ports: 
      - "8086:8086"
    restart: unless-stopped
  mosquitto:
    image: eclipse-mosquitto:1.6
    ports: 
        - "1883:1883"
  elasticsearch:
    image: elasticsearch:7.17.2
    environment:
      - "discovery.type=single-node"
      - "cluster.name=mars"
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ports:
      - "9200:9200"
  rasa:
    image: rasa/rasa:1.2.3-full
    ports:
      - "5005:5005"
    volumes:
      - ./rasa/models:/app/models
    command:
      - run
      - --cors
      - "*"
  analytics:
    image: vertigoio/vertigo-analytics-server
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=is4DQpHF8XkvNJRm5KNJOtjlKIpfVc2G
    depends_on:
      - influxdb
    ports:
      - "4562:4562"
    restart: unless-stopped
  tomcat:
    depends_on: ["postgresql", "redis", "influxdb", "mosquitto", "elasticsearch", "rasa", "analytics"]
    environment:
      - ANALYTICS_URL=analytics:4562
      - ES_URL=http://elasticsearch:9200
    build: ./tomcat
    volumes:
      - "./tomcat/mars.xml:/usr/local/tomcat/conf/Catalina/localhost/mars.xml"
      - "./tomcat/marsApiKeys.properties:/usr/local/tomcat/marsconf/marsApiKeys.properties"
    ports:
      - "8080:8080"